### ISSUE TITLE
Type mismatch in `KeyAuthorization.fromRpc()` return type

### ISSUE THREAD

**Issue by alx-khramov** [wevm/ox#290]
### Check existing issues

- [x] I checked there isn't [already an issue](https://github.com/wevm/ox/issues) for the bug I encountered.

### Ox Version

`ox@0.14.26` through `ox@0.14.30` (at least)
The issue was introduced in #262 which added support for TIP-1049 (admin access keys)

### Description

The `fromRpc()` function in `ox/tempo/KeyAuthorization.ts` returns an object that does not satisfy its declared return type `Signed`. Specifically, the fields `account` and `isAdmin` are typed as optional/potentially `undefined`, but the `Signed` type signature requires them to be non-optional.

### Current Behavior

TypeScript compiler reports:
```
Type error TS2322: Type '{ account?: `0x${string}` | undefined; isAdmin?: true | undefined; witness?: `0x${string}` | undefined; signature: SignatureEnvelope.SignatureEnvelope<bigint, number>; ... 5 more ...; chainId: bigint; }' is not assignable to type 'Signed<bigint, number, `0x${string}`>'.
  Type '{ account?: `0x${string}` | undefined; isAdmin?: true | undefined; ... }' is not assignable to type '{ account: `0x${string}`; isAdmin: boolean; }'.
    Types of property 'account' are incompatible.
      Type '`0x${string}` | undefined' is not assignable to type '`0x${string}`'.
```

### Expected Behavior

KeyAuthorization.fromRpc() should return a value that satisfies the Signed type without TypeScript errors. The function already returns all required fields at runtime; the issue is purely a type annotation mismatch.

The return value should have:

`account` typed as `0x${string}` (not `0x${string} | undefined`)
`isAdmin` typed as `boolean` (not `boolean | undefined`)
Or the Signed type should reflect that these fields are optional/conditional.

### Steps To Reproduce

Just check the Minimal Reproducible Example

### Link to Minimal Reproducible Example

[https://www.typescriptlang.org/play/](https://www.typescriptlang.org/play/?target=99&moduleResolution=99&module=1&ts=5.7.3#code/C4TwDgpgBAEhAeUC8UAGAGeASA3gZ2ACcBLAOwHMBfVAKBoHp6oBBAY2AFcBDAGylEh4oAM0IB7ALZQxiABSEIYcQBMOrCMoCUDJgBUAFtAWdCpfuAgAuKAoCOHYgqFdWrMR1LAoXUsqjE8ZmUJMm8hUjFSAFoxMGBiSN4aAWgAZWJyUg1kKBwaKG9lZSc8azh4fKhWfS4yAEllawAjDLJgSpTrAHI8CFYwACYAVgA2AGsARi7KvAzSLhMrb1IQSpc3D2AyhALd3cYoQATCKAAlAFEARQBVOvOAEShZCOjY+MSebQKAoJDSZrExDwID49gdjudrrczg8npEYnEEvMPjRKHQDgZoGQwBwvJ1vK53J5ln5vsFQlwFNIEe9khZTmBWDk8gVqrVSA1thUCmMICAObAEJUeSBdBZur1+sNxlMZnMFhwFNYfKsCutCcAAPycvb7JjHADyAAVdHV9QA5ZgAGUerBBTWgHmUEGEZA0n38gTJpC1UCaAKBIIKYKgRpN5qtNrtDt8ztdWhRaL0+gCIg87ERInEUhkAAF0AA6CYAFnzAGZ0D0oABpXnMHH6MQkABeC0R+eAQhqznMkF9HHIlh0UDqXlYPFqEiEwDENggJjM6Uy2VkAHdk9VZ-ZHBBnATNlAAGQen5kbQHJo4-wd-wSMBAiQQTytyJVHxdLzkbiEHzACDQYANr0IjEBAPDKEICABO0whpm8ZiiJIJwMrIXD1o2xAtnB1hIawmjWIuWR+MyUDooYQErsQPB8PaUCOrGhH+MI-CGP4pDYl4yhiDupDvlAShiAAbsQTrMRAEiVG4pAEMeXo5KhAHoZhbakr8UAahqtExi6hESZE0lqvuKDyQ2zbPqQ+YGUS6maU62kaHQBTGAqZjEaqRQlEqaGmXB+bCg0AA0lQsjU9SNFAABCGR1J4KFeRhZn5qyoWaIFex4sZikJcKoqQKluyzJk8qKt4cVKZE+YFfMix5UGTCpEowJ+LEEDftOhDSKQPAgIU4GicBoG9ZJyjEHBvBdUFJFMHUTEqaEKZ0XZyj+cxKYugNUArpEvE0aEAHQGITQAFZ9O0ez5udsizWYGk4DJvzWEQHDQJQUDWDglApRNBzTfiGxEvNWlxstAGrSBYEbVtXg7WYe3SEdJ1QBAI2GIQE3nfmKF7kSACESAoAtcZqbkv3qlAL1vR9NWTVAgCJhBFVwAOLYXOznZAdx3sFAEhcN1EReDUAnQJZwD0Fdy0Xl4BHZCkm4OE4okSNjlSoqiQ45RAqSsCQcSI4Q4iENYCESDhsiaK+ZhOaYyxwxzXghHgswUCTmyi56qlrWBeA0JJ0lOBwPBbFAUt+CgRsm8RSXsmFXSYFMeV+dHmBcE0rBdPHvLq+KfSDKMkxp7KhWLBTeUHMLxJ3eSlJ83x4hCU6fiAEmEG2UdR0a2YTTfV6ElsMezJ0otoQA)

### Anything else?

The issue is related to https://github.com/wevm/ox/issues/272

### How I found the issue
While upgrading dependencies in the [reef-knot](https://github.com/lidofinance/reef-knot) monorepo, I bumped `viem` from 2.44.4 to 2.54.6. This version pulls in `ox@0.14.30` as a transitive dependency.

When running `next build` in the demo app (`apps/demo-react`), the TypeScript type checker encountered a type mismatch error in `ox/tempo/KeyAuthorization.ts:537`.

The issue occurs because:
- The project uses `moduleResolution: "node10"` which resolves to raw `.ts` source files in ox's node_modules instead of compiled `.d.ts` definitions
- `skipLibCheck: true` doesn't apply to raw `.ts` source files, only `.d.ts` files
- The raw `.ts` file contains an unresolved type inconsistency that wasn't caught before

The error in the log:
```
info  - Linting and checking validity of types ...Failed to compile.

../../node_modules/viem/node_modules/ox/tempo/KeyAuthorization.ts:537:3
Type error: Type '{ account?: `0x${string}` | undefined; isAdmin?: true | undefined; wit
ness?: `0x${string}` | undefined; signature: SignatureEnvelope.SignatureEnvelope<bigint,
 number>; ... 5 more ...; chainId: bigint; }' is not assignable to type 'Signed<bigint, 
number, `0x${string}`>'.
  Type '{ account?: `0x${string}` | undefined; isAdmin?: true | undefined; witness?: `0x
${string}` | undefined; signature: SignatureEnvelope.SignatureEnvelope<bigint, number>; 
... 5 more ...; chainId: bigint; }' is not assignable to type '{ address: `0x${string}`;
 chainId: bigint; expiry?: number | null | undefined; limits?: readonly TokenLimit<bigin
t, number, `0x${string}`>[] | undefined; scopes?: readonly Scope<`0x${string}`>[] | unde
fined; type: "p256" | ... 1 more ... | "webAuthn"; witness?: `0x${string}` | undefined; 
} & { ...; } & { ...; }'.
    Type '{ account?: `0x${string}` | undefined; isAdmin?: true | undefined; witness?: `
0x${string}` | undefined; signature: SignatureEnvelope.SignatureEnvelope<bigint, number>
; ... 5 more ...; chainId: bigint; }' is not assignable to type '{ account: `0x${string}
`; isAdmin: boolean; }'.
      Types of property 'account' are incompatible.
        Type '`0x${string}` | undefined' is not assignable to type '`0x${string}`'.
          Type 'undefined' is not assignable to type '`0x${string}`'.

  535 |     : undefined
  536 | 
> 537 |   return {
      |   ^
  538 |     address: keyId,
  539 |     chainId: chainId === '0x' ? 0n : Hex.toBigInt(chainId),
  540 |     ...(expiry != null ? { expiry: Number(expiry) } : {}),
```

### Impact
This type error blocks downstream projects (like viem 2.52+, which includes ox/tempo support) from building with strict TypeScript checking, even though the code works correctly at runtime. Projects using next build with skipLibCheck: false fail during type-checking.

### Affected downstream
viem >= 2.52.0 (includes ox/tempo in its chain definitions)
Any wagmi/viem consumers with strict TS checking in their Next.js/build pipelines
